[package]
name = "fixed-exp"
version = "0.1.0"
authors = ["toasteater <48371905+toasteater@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed = "1"
typenum = "1"
num-traits = "0.2"